applications/home/urls.py
from django.urls import path

from . import views

app_name = "home_app"

urlpatterns = [

    path(
        '', 
        views.QHola.as_view(),
        name='publico',
    ),
    
    path(
        'contacto', 
        views.ContatoCreateView.as_view(),
        name='contacto',
    ),

]

tony/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/home/models.py
from django.db import models

class Prueba(models.Model):
    hola = models.CharField(max_length=30)

class Contacto(models.Model):
    
    ASUNTO= ( 
    ("1", "Cotizacion"), 
    ("2", "Solicitud de informacion"), 
    
) 
    name = models.CharField(max_length=35)

    mail = models.EmailField(max_length=100)

    telefono = models.IntegerField()

    asunto = models.CharField(
        max_length=30,
        choices = ASUNTO,)

    mensaje = models.TextField(max_length=150)

applications/home/views.py
from venv import create
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from django.http import HttpResponse
from . models import Contacto

class QHola(TemplateView):
    template_name = "home/index.html"

class ContatoCreateView(CreateView):
    template_name = "home/contacto.html"
    model = Contacto
    fields = "__all__"
    success_url = '.'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-MX">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
  <link rel="stylesheet" href="{% static 'css/foundation-icons/foundation-icons.css' %}">
  <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  <link rel="stylesheet" href="{% static 'prueba.css' %}">
  
  <title>{% block title %}{% endblock title %}Tony</title>
  {% block css %}{% endblock css %}
</head>
<body>

  {% block content %}
  {% endblock content %}

  {% block js %}
  
  {% endblock js %}
</body>
<script src="{% static 'js/vendor/jquery.js' %}"></script>
<script src="{% static 'js/vendor/what-input.js' %}"></script>
<script src="{% static 'js/vendor/foundation.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
</html>

templates/home/base_home.html
{% extends "panel.html" %}

{% load static %} 

{% block css %}
 
{% endblock css %} 

{% block js %}

{% endblock js %}

templates/home/contacto.html
{% extends "home/base_home.html" %} 
{% load static %} 
{% block panel-content %}
<h1>Vista  contacto</h1>

<form method="POST" enctype="multipart/form-data">
 
    <!-- Security token -->
    {% csrf_token %}
 
    <!-- Using the formset -->
    {{ form.as_p }}
     
    <input type="submit" value="Guardar">
</form>

{% endblock panel-content %}

templates/home/index.html
{% extends "home/base_home.html" %} 
{% load static %} 
{% block panel-content %}

<div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
    <div class="orbit-wrapper">
      <div class="orbit-controls">
        <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
        <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
      </div>
      <ul class="orbit-container">
        <li class="is-active orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static 'img/abstract-banner-technology-stripes-geometric-diagonal-pink-blue-background-free-vector.jpg' %}" alt="Space">
            <figcaption class="orbit-caption">Space, the final frontier.</figcaption>
          </figure>
        </li>
        <li class="orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static 'img/abstract-banner-technology-stripes-geometric-diagonal-pink-blue-background-free-vector.jpg' %}" alt="Space">
            <figcaption class="orbit-caption">Lets Rocket!</figcaption>
          </figure>
        </li>
        <li class="orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static 'img/abstract-banner-technology-stripes-geometric-diagonal-pink-blue-background-free-vector.jpg' %}" alt="Space">
            <figcaption class="orbit-caption">Encapsulating</figcaption>
          </figure>
        </li>
        <li class="orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static 'img/abstract-banner-technology-stripes-geometric-diagonal-pink-blue-background-free-vector.jpg' %}" alt="Space">
            <figcaption class="orbit-caption">Outta This World</figcaption>
          </figure>
        </li>
      </ul>
    </div>
    <nav class="orbit-bullets">
      <button class="is-active" data-slide="0">
        <span class="show-for-sr">First slide details.</span>
        <span class="show-for-sr" data-slide-active-label>Current Slide</span>
      </button>
      <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
      <button data-slide="2"><span class="show-for-sr">Third slide details.</span></button>
      <button data-slide="3"><span class="show-for-sr">Fourth slide details.</span></button>
    </nav>
  </div>


  <div class="media-object stack-for-small">
    <div class="media-object-section">
      <div class="thumbnail">
        <img src="{% static 'img/ll.jpeg' %}" alt="Space">
      </div>
    </div>
    <div class="media-object-section">
      <h4>Software.</h4>
      <p>Desarrollamos software a la medida, mejorando e integrando plataformas tecnológicas para diferentes entidades del sector público y privado.</p>
    </div>
  </div>
  <br>
  <div class="media-object">
    <div class="media-object-section">
      <h4>Why is it so important to dream?</h4>
      <p>So, once we've made the plant, how do we go out? Hope you have something more elegant in mind than shooting me in the head? A kick. What's a kick? This, Ariadne, would be a kick.</p>
      <p>What is the most resilient parasite? Bacteria? A virus? An intestinal worm? An idea. Resilient... highly contagious. Once an idea has taken hold of the brain it's almost impossible to eradicate. An idea that is fully formed - fully understood - that sticks; right in there somewhere.</p>
    </div>
    <div class="media-object-section bottom">
      <div class="thumbnail">
        <img src= "{% static 'img/not2.jpeg' %}">
      </div>
    </div>
  </div>

{% endblock panel-content %}

templates/panel.html
{% extends "base.html" %} 

{% load static %}

{% block content %}
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
    <div class="title-bar-title">Menu</div>
  </div>
  
  <div class="top-bar" id="responsive-menu">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Tony</li>
        <li><a href="{% url 'home_app:publico' %}">Inicio</a></li>
        <li class="has-submenu">
          <a href="#0">Soluciones</a>
          <ul class="submenu menu vertical" data-submenu>
            <li><a href="#0">Desarrollo de software</a></li>
            <li><a href="#0">Automatizacion</a></li>
            <li><a href="#0">Three</a></li>
          </ul>
        </li>
        <li><a href="#0">Nosotros</a></li>
        <li><a href="{% url 'home_app:contacto' %}">Contacto</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar"></li>
        <li><button type="button" class="button">Buscar</button></li>
      </ul>
    </div>
  </div>

  {% block panel-content %}
  {% endblock panel-content %}

  <div class="row column">
    <hr>
    <ul class="menu">
      <li>Yeti Store</li>
      <li><a href="#">Home</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
      <li class="float-right">Copyright 2016</li>
    </ul>
  </div>

  

    

{% endblock content %}